import { DemoMailbox } from './transport'
import { browserStorage } from '../finance/storage'
import type { SavingsGoal } from '../finance/goals'
import { DeviceConnection } from './DeviceConnection'
import { completed } from '../workspace/state'
import './letter.css'
export function PhysicalLetterScreen({identity,goal,onFinish}:{identity:string;goal:SavingsGoal|null;onFinish:()=>void}) {
 const box=new DemoMailbox(identity,browserStorage(identity)).snapshot()
 return <main className="finance-page letter-page physical-letter-page"><span className="section-number">05 / DEVICE DELIVERY</span><h1>A little letter<br/>for {box.companion?.name || 'okanegotchi'}.</h1><div className="mail-layout"><section className="letter-review"><span className="section-number">5.1 / YOUR LETTER</span><h2>Dear {box.companion?.name || 'okanegotchi'},</h2><dl><dt>Pet name</dt><dd>{box.companion?.name || 'Choose a name in Pet'}</dd><dt>Pet type</dt><dd>{box.companion?.pet || 'Choose a pet'}</dd><dt>Fund / savings goal</dt><dd>{goal?.name || 'Create a goal in Goals'}</dd></dl><p className="mail-signature">Little steps, together. &lt;3</p><p className="mail-letter-note">Send a letter to {box.companion?.name || 'your companion'} to give an update on your savings progress.</p></section><section className="mail-stage-card"><span className="section-number">5.2 / DEVICE DELIVERY</span><div className="mail-stage" aria-hidden="true"><div className="mail-envelope"><div className="envelope-back"/><div className="mail-paper"><span>♡</span><span>YOUR LITTLE GOAL</span><i/><i/></div><div className="envelope-front"/><div className="envelope-flap"/><span className="envelope-address">TO: YOUR EGG</span></div></div><p role="status">Waiting for a compatible, verified device connection.</p><button className="primary-button" disabled>Send to device</button><p className="mail-note">Your letter stays here until the device service and compatible firmware are ready.</p></section></div><span className="section-number">5.3 / CONNECTION</span><DeviceConnection identity={identity} name={box.companion?.name}/><button className="primary-button" disabled={!box.companion||!box.preferences||!goal} onClick={onFinish}>{completed(browserStorage(identity),identity)?'Back to dashboard':'Finish setup & open dashboard ↗'}</button></main>
}
