import { test } from 'node:test'
import assert from 'node:assert/strict'
import { DemoProvider } from '../src/finance/provider.ts'
import { accounts, transactions, totals } from '../src/finance/fixtures.ts'
import { storageKey } from '../src/finance/storage.ts'
const memory = () => { const data = new Map<string,string>(); return { getItem: (k:string) => data.get(k) ?? null, setItem: (k:string,v:string) => { data.set(k,v) } } }
const make = (storage = memory(), id = 'guest') => new DemoProvider(id, storage, () => '2026-09-26T12:00:00.000Z', async () => {})
test('connect validates selection and deduplicates concurrent requests', async () => { const p=make(); await assert.rejects(p.connect('clover', [])); await assert.rejects(p.connect('clover',['pocket-credit'])); await Promise.all([p.connect('clover',['clover-checking']),p.connect('clover',['clover-checking','clover-savings'])]); assert.equal(p.snapshot().connections.length,1); assert.equal(p.snapshot().accounts.length,2) })
test('cancel does not mutate or persist', async () => { const p=make(); const c=new AbortController(); c.abort(); await assert.rejects(p.connect('clover',['clover-checking'],c.signal)); assert.equal(p.snapshot().accounts.length,0) })
test('persistence is isolated by identity', async () => { const s=memory(); await make(s).connect('clover',['clover-checking']); assert.equal(make(s).snapshot().accounts.length,1); assert.equal(make(s,'user:1').snapshot().accounts.length,0) })
test('malformed, obsolete, and invalid storage recover empty', () => { const s=memory(); for (const value of ['{','{"version":2,"connections":[]}','{"version":1,"connections":[{"institutionId":"fake"}]}']) { s.setItem(storageKey('guest'),value); assert.equal(make(s).snapshot().accounts.length,0) } })
test('storage failures retain in-memory data', async () => { const p=make({getItem:()=>{throw Error()},setItem:()=>{throw Error()}}); await p.connect('clover',['clover-checking']); assert.equal(p.snapshot().accounts.length,1); assert.equal(p.storageAvailable,false) })
test('refresh failure retains timestamp and transactions; retry is idempotent', async () => { const p=make(); await p.connect('clover',['clover-checking']); const before=p.snapshot(); p.simulateRefreshFailure(); await assert.rejects(p.refresh('clover')); assert.equal(p.snapshot().connections[0].status,'stale'); assert.equal(p.snapshot().connections[0].refreshedAt,before.connections[0].refreshedAt); assert.deepEqual(p.snapshot().transactions,before.transactions); await p.refresh('clover'); await p.refresh('clover'); assert.deepEqual(p.snapshot(),before) })
test('attention requires reconnect and connection failures can retry', async () => { const p=make(); p.simulateConnectFailure(); await assert.rejects(p.connect('clover',['clover-checking'])); assert.equal(p.snapshot().accounts.length,0); await p.connect('clover',['clover-checking']); p.attention('clover'); await assert.rejects(p.refresh('clover')); await p.reconnect('clover'); assert.equal(p.snapshot().connections[0].status,'connected') })
test('disconnect and reset remove associated records', async () => { const p=make(); await p.connect('clover',['clover-checking']); await p.connect('sunny',['sunny-savings']); await p.disconnect('clover'); assert.equal(p.snapshot().accounts.length,1); assert.ok(p.snapshot().transactions.every(t=>t.accountId==='sunny-savings')); await p.reset(); assert.equal(p.snapshot().transactions.length,0) })
for (const operation of ['reset','disconnect','dispose'] as const) test(`late refresh/connect cannot survive ${operation}`, async () => { let release=()=>{}; let delayed=false; const p=new DemoProvider('guest',memory(),()=> '2026-09-26T12:00:00.000Z',()=> delayed ? new Promise<void>(r=>{release=r}) : Promise.resolve()); await p.connect('clover',['clover-checking']); delayed=true; const pending=p.refresh('clover'); if(operation==='reset') await p.reset(); else if(operation==='disconnect') await p.disconnect('clover'); else p.dispose(); release(); await assert.rejects(pending); if(operation!=='dispose') assert.equal(p.snapshot().accounts.length,0) })
test('late connect after identity disposal is ignored', async () => { let release=()=>{}; const s=memory(); const p=new DemoProvider('guest',s,()=>'',()=>new Promise<void>(r=>{release=r})); const pending=p.connect('clover',['clover-checking']); p.dispose(); release(); await assert.rejects(pending); assert.equal(make(s).snapshot().accounts.length,0) })
test('money separates debt, transfers, refunds, and pending from posted purchases', () => { const result=totals(accounts,transactions); assert.equal(result.cash,832605); assert.equal(result.owed,18450); assert.equal(result.spending,4330); assert.equal(transactions.length,25); const pair=transactions.filter(t=>t.transferRef==='demo-transfer-1'); assert.equal(pair.length,2); assert.equal(pair[0].amount,pair[1].amount) })

for (const action of ['reset', 'disconnect'] as const) test(`late connect is invalidated by ${action}`, async () => { let release=()=>{}; const p=new DemoProvider('guest',memory(),()=>'',()=>new Promise<void>(r=>{release=r})); const pending=p.connect('clover',['clover-checking']); await p[action](...(action==='disconnect' ? ['clover'] : []) as [string]); release(); await assert.rejects(pending); assert.equal(p.snapshot().accounts.length,0) })
