"""Build-time PNG/sprite-sheet -> flash data. No runtime PNG library needed.

Catalog source crops select explicit 32x32 rectangles from sheets. Exact canonical
palette colors become 4-bit indices; other art keeps RGB565 + binary alpha.
Partial transparency is rejected, never silently composited or recolored.
"""
import argparse
import json
from pathlib import Path
from PIL import Image, ImageDraw
from check_assets import validate, STATES

ROOT = Path(__file__).resolve().parents[1]
def rgb(color): return tuple(bytes.fromhex(color[1:]))
def rgb565(c): return ((c[0]>>3)<<11)|((c[1]>>2)<<5)|(c[2]>>3)
def source_path(root, value):
    p=(root/value).resolve()
    if not p.is_relative_to(root.resolve()): raise ValueError('source escapes catalog folder')
    return p
def image_for(frame, root):
    w,h=frame['size']; src=frame['source']
    if src['kind']=='png':
        im=Image.open(source_path(root,src['path'])).convert('RGBA');x,y,cw,ch=src['crop']
        if x+cw>im.width or y+ch>im.height: raise ValueError('crop outside image: '+frame['id'])
        return im.crop((x,y,x+cw,y+ch))
    im=Image.new('RGBA',(w,h));d=ImageDraw.Draw(im);color=frame['_color']
    if src['shape']=='circle':d.ellipse((2,2,w-3,h-3),fill=color)
    elif src['shape']=='diamond':d.polygon([(w//2,1),(w-2,h//2),(w//2,h-2),(1,h//2)],fill=color)
    else:d.rectangle((2,2,w-3,h-3),fill=color)
    if w==32:d.rectangle((10,11,12,13),fill='#222222');d.rectangle((20,11,22,13),fill='#222222')
    return im
def pack(im, colors):
    rgba=list(im.getdata())
    if any(p[3] not in (0,255) for p in rgba): raise ValueError('use hard pixel edges: alpha must be 0 or 255')
    indexed=all(p[3]==0 or p[:3] in colors[1:] for p in rgba)
    if indexed:
        indices=[0 if p[3]==0 else colors.index(p[:3],1) for p in rgba]
        return True,bytes((indices[i]<<4)|(indices[i+1] if i+1<len(indices) else 0) for i in range(0,len(indices),2)),b''
    data=b''.join(rgb565(p).to_bytes(2,'little') for p in rgba)
    mask=bytearray((len(rgba)+7)//8)
    for i,p in enumerate(rgba):
        if p[3]:mask[i//8]|=0x80>>(i%8)
    return False,data,bytes(mask)
def compile_catalog(path,out,preview=None):
    c=json.loads(path.read_text(encoding='utf-8'));validate(c)
    colors=[rgb(x) for p in c['palettes'] if p['id']==c['import_palette'] for x in p['colors']]
    lines=['// Generated by tools/compile_assets.py; edit the catalog and PNG sources.','#include "../assets.hpp"','namespace okanegachi::assets {']
    frames={};clips={};scenes={};images=[];total=0;report=[]
    def array(name,data):lines.append('static const uint8_t '+name+'[] = {'+','.join(str(n) for n in data)+'};')
    def emit_frame(f,im):
        nonlocal total
        i=len(frames);name='frame_'+str(i);frames[f['id']]=name
        indexed,data,mask=pack(im,colors);array(name+'_data',data)
        if mask:array(name+'_mask',mask)
        anchors=f.get('anchors',{});points=','.join('{%d,%d}'%tuple(anchors.get(k,[0,0])) for k in ('feet','head','neck','body'))
        lines.append('static const Frame '+name+'={'+json.dumps(f['id'])+f',{im.width},{im.height},{str(indexed).lower()},{name}_data,'+(name+'_mask' if mask else 'nullptr')+','+points+'};')
        total+=len(data)+len(mask);report.append({'id':f['id'],'format':'indexed4' if indexed else 'rgb565-mask1','bytes':len(data)+len(mask)})
        return name
    for f in c['frames']:
        if f['source']['kind']=='placeholder':f['_color']=colors[f['source']['palette_index']]+(255,)
        im=image_for(f,path.parent);emit_frame(f,im);images.append(im)
    lines.append('const Palette palettes[] = {'+','.join('{'+json.dumps(p['id'])+',{'+','.join(str(rgb565(rgb(x))) for x in p['colors'])+'}}' for p in c['palettes'])+'};')
    lines.append('const size_t palette_count=sizeof(palettes)/sizeof(palettes[0]);')
    for i,clip in enumerate(c['clips']):
        name='clip_'+str(i);clips[clip['id']]=name
        lines.append('static const Step '+name+'_steps[]={'+','.join('{&'+frames[s['frame']]+','+str(s['duration_ms'])+'}' for s in clip['frames'])+'};')
        lines.append('static const Clip '+name+'={'+json.dumps(clip['id'])+','+name+'_steps,'+str(len(clip['frames']))+','+str(clip['mode']=='loop').lower()+'};')
    lines.append('const Character characters[]={'+','.join('{'+json.dumps(ch['id'])+',{'+','.join('&'+clips[ch['animations'][s]] for s in STATES)+'}}' for ch in c['characters'])+'};')
    lines.append('const size_t character_count=sizeof(characters)/sizeof(characters[0]);')
    accessories=[]
    for a in c['accessories']:
        for v in a['variants']:
            for ch in v['characters']:
                accessories.append('{'+','.join([json.dumps(a['id']),json.dumps(ch),'&'+frames[v['frame']],str(('feet','head','neck','body').index(v['anchor'])),'{%d,%d}'%tuple(v['origin']),'{%d,%d}'%tuple(v['offset']),str(v['layer']=='front').lower()])+'}')
    lines.append('const Accessory accessories[]={'+(','.join(accessories) if accessories else '{nullptr,nullptr,nullptr,0,{0,0},{0,0},false}')+'};')
    lines.append('const size_t accessory_count='+str(len(accessories))+';')
    backgrounds={}
    for b in c['backgrounds']:
        if b['kind']=='solid':backgrounds[b['id']]=(rgb565(rgb(b['color'])),'nullptr')
        else:
            im=Image.open(source_path(path.parent,b['path'])).convert('RGBA')
            if list(im.size)!=b['size']:raise ValueError('background size mismatch')
            name=emit_frame({'id':'background.'+b['id']},im);backgrounds[b['id']]=(0,'&'+name)
    for i,s in enumerate(c['scenes']):
        name='scene_'+str(i);scenes[s['id']]=name;props=[]
        for p in s['props']:props.append('{&'+frames[p['frame']]+',{%d,%d},%d,%s}'%(*p['screen_xy'],p['scale'],str(p['layer']=='front').lower()))
        if props:lines.append('static const Prop '+name+'_props[]={'+','.join(props)+'};')
        color,bg=backgrounds[s['background']]
        lines.append('static const Scene '+name+'={'+json.dumps(s['id'])+f',{color},{bg},'+'{%d,%d},%d,'%(*s['character_root'],s['scale'])+(name+'_props' if props else 'nullptr')+','+str(len(props))+'};')
    lines.append('const Scene* bindings[11]={'+','.join('&'+scenes[c['scene_bindings'][s]] for s in STATES)+'};')
    lines.append('const size_t pixel_bytes='+str(total)+';\n}')
    if total>768*1024:raise ValueError('pixel budget exceeds 768 KiB; reduce art or review flash partition')
    out.parent.mkdir(parents=True,exist_ok=True);out.write_text('\n'.join(lines)+'\n',encoding='utf-8')
    if preview:
        preview.mkdir(parents=True,exist_ok=True)
        sheet=Image.new('RGB',(8*128,((len(images)+7)//8)*128),'#bbbbbb')
        for i,im in enumerate(images):sheet.paste(im.resize((128,128),Image.Resampling.NEAREST),(i%8*128,i//8*128),im.resize((128,128),Image.Resampling.NEAREST))
        sheet.save(preview/'frames.png');(preview/'asset-report.json').write_text(json.dumps({'pixel_bytes':total,'frames':report},indent=2)+'\n')
    print(f'{len(images)} frames, {total} flash pixel bytes -> {out}')
    return report
if __name__=='__main__':
    ap=argparse.ArgumentParser();ap.add_argument('--catalog',type=Path,default=ROOT/'assets/catalog.example.json');ap.add_argument('--output',type=Path,default=ROOT/'build/assets/custom_assets.cpp');ap.add_argument('--preview',type=Path,default=ROOT/'build/assets');a=ap.parse_args();compile_catalog(a.catalog,a.output,a.preview)
