"""Compile the committed v1 JSON Schemas to bounded, allocation-free C++ checks.

Fails on unsupported validation keywords; does not silently ignore schema drift.
"""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
META={'$schema','title','description','$defs'}
SUPPORTED=META|{'$ref','type','properties','required','additionalProperties','items','maxItems','minItems','enum','const','minimum','maximum','minLength','maxLength','pattern','format','anyOf','oneOf','allOf','if','then','else'}
functions=[]
def literal(v):
    return json.dumps(v,ensure_ascii=True,separators=(',',':'))
def emit(rule,doc):
    if set(rule)-SUPPORTED: raise ValueError(f'Unsupported keywords: {set(rule)-SUPPORTED}')
    name=f'node_{len(functions)}'; functions.append('')
    lines=[]
    def need(expr): lines.append(f'if (!({expr})) return false;')
    if '$ref' in rule:
        ref=rule['$ref']; assert ref.startswith('#/$defs/')
        need(f'{emit(doc["$defs"][ref.rsplit("/",1)[1]],doc)}(v)')
    typ=rule.get('type')
    type_expr={'object':'v.is<JsonObjectConst>()','array':'v.is<JsonArrayConst>()','string':'v.is<const char*>()','boolean':'v.is<bool>()','null':'v.isNull()','integer':'v.is<double>() && !v.is<bool>() && std::isfinite(v.as<double>()) && std::floor(v.as<double>())==v.as<double>()'}
    if typ: need(type_expr[typ])
    if 'const' in rule:
        val=rule['const']
        kind='boolean' if isinstance(val,bool) else 'string' if isinstance(val,str) else 'integer'
        need(type_expr[kind]); need(f'v == {literal(val)}')
    if 'enum' in rule: need(' || '.join(f'v == {literal(x)}' for x in rule['enum']))
    if 'minimum' in rule: need(f'v.as<double>() >= {rule["minimum"]}.0')
    if 'maximum' in rule: need(f'v.as<double>() <= {rule["maximum"]}.0')
    if 'minLength' in rule or 'maxLength' in rule:
        lines.append('const auto s=v.as<JsonString>(); const int n=utf8_length(s.c_str(),s.size());')
        need(f'n >= {rule.get("minLength",0)} && n <= {rule.get("maxLength",8192)}')
    fmt=rule.get('format')
    if fmt:
        expr={'uuid':'valid_uuid(v.as<std::string>())','date':'utc_millis(v.as<std::string>(),true).has_value()','date-time':'utc_millis(v.as<std::string>()).has_value()'}[fmt]
        need(expr)
    if 'pattern' in rule:
        # These patterns are implemented by the more specific validators above.
        p=rule['pattern']
        if fmt=='uuid': assert p==r'^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'
        elif fmt=='date': assert p==r'^\d{4}-\d{2}-\d{2}$'
        elif fmt=='date-time': assert p==r'^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{1,3})?Z$'
        else:
            assert p==r'^[A-Za-z0-9][A-Za-z0-9._+-]*$'
            need('valid_firmware_version(v.as<std::string>())')
    for key in rule.get('required',[]): need(f'v.as<JsonObjectConst>().containsKey({literal(key)})')
    for key,child in rule.get('properties',{}).items():
        fn=emit(child,doc)
        lines.append(f'if (v.as<JsonObjectConst>().containsKey({literal(key)}) && !{fn}(v[{literal(key)}])) return false;')
    if rule.get('additionalProperties') is False:
        keys=rule.get('properties',{})
        allowed=' || '.join(f'std::strcmp(p.key().c_str(), {literal(k)}) == 0' for k in keys) or 'false'
        lines.append(f'for (JsonPairConst p:v.as<JsonObjectConst>()) if (!({allowed})) return false;')
    if 'maxItems' in rule: need(f'v.as<JsonArrayConst>().size() <= {rule["maxItems"]}')
    if 'minItems' in rule: need(f'v.as<JsonArrayConst>().size() >= {rule["minItems"]}')
    if 'items' in rule: lines.append(f'for (auto x:v.as<JsonArrayConst>()) if (!{emit(rule["items"],doc)}(x)) return false;')
    for keyword in ('anyOf','allOf','oneOf'):
        if keyword in rule:
            calls=[f'{emit(x,doc)}(v)' for x in rule[keyword]]
            need(' || '.join(calls) if keyword=='anyOf' else ' && '.join(calls) if keyword=='allOf' else '('+' + '.join(f'int({x})' for x in calls)+') == 1')
    if 'if' in rule:
        condition=emit(rule['if'],doc); yes=emit(rule.get('then',{}),doc); no=emit(rule.get('else',{}),doc)
        need(f'({condition}(v) ? {yes}(v) : {no}(v))')
    functions[int(name.split('_')[1])]=f'static bool {name}(JsonVariantConst v) {{\n  (void)v;\n  '+'\n  '.join(lines)+'\n  return true;\n}\n'
    return name
entry=[]
for kind in ('request','response','error'):
    path=ROOT.parent/'mvp'/f'device-{("sync-" if kind!="error" else "")}{kind}.schema.json'
    d=json.loads(path.read_text()); entry.append((kind,emit(d,d)))
out='// Generated by tools/generate_schema.py; do not edit.\n'
out+='\n'.join(f'static bool node_{i}(JsonVariantConst);' for i in range(len(functions)))+'\n'
out+='\n'.join(functions).replace('\n  \n','\n\n')
out+='static bool schema_check(JsonVariantConst v, Schema schema) {\n switch(schema) {\n'
out+='\n'.join(f'case Schema::{k.title()}: return {n}(v);' for k,n in entry)
out+='\n } return false;\n}\n'
target=ROOT/'src/generated/schema_checks.inc'; target.parent.mkdir(parents=True,exist_ok=True); target.write_text(out)
print(f'Generated {len(functions)} schema checks')
base=(ROOT.parent/'mvp/examples/sync-response.json').read_text(encoding='utf-8')
if ')demo"' in base:raise ValueError('fixture collides with C++ raw-string delimiter')
(ROOT/'src/generated/demo_base.inc').write_text('R"demo('+base+')demo"\n',encoding='utf-8')
